import networkx as nx
import os
import logging
from itertools import combinations

logger = logging.getLogger(__name__)


def break_cycles_make_dag(G):
    G = G.copy()
    try:
        while not nx.is_directed_acyclic_graph(G):
            cycles = list(nx.simple_cycles(G))
            if not cycles:
                break
            cycle = cycles[0]
            weakest = None
            edge_to_remove = None
            for i in range(len(cycle)):
                u = cycle[i]
                v = cycle[(i + 1) % len(cycle)]
                w = G[u][v].get('weight', 0.0)
                if weakest is None or w < weakest:
                    weakest = w
                    edge_to_remove = (u, v)
            if edge_to_remove:
                G.remove_edge(*edge_to_remove)
        return G
    except Exception:
        return G


def generate_learning_space_from_dag(G, items=None):
    if items is not None:
        Gsub = G.subgraph(items).copy()
    else:
        Gsub = G.copy()

    if not nx.is_directed_acyclic_graph(Gsub):
        Gsub = break_cycles_make_dag(Gsub)

    states = set([frozenset()])
    try:
        order = list(nx.topological_sort(Gsub))
    except Exception:
        order = list(Gsub.nodes())

    for item in order:
        preds = set(Gsub.predecessors(item))
        new_states = set()
        for s in states:
            if preds.issubset(s):
                new_states.add(s | {item})
        states |= new_states

    logger.info('Generated %d ideals from DAG (items=%d)', len(states), len(Gsub.nodes()))
    return states


def count_ideals_from_dag(G, items=None, cap=None):
    """Count number of ideals (closed sets) generated by DAG over given items.
    This does not enumerate sets; it only counts using dynamic programming.
    If cap is provided and count exceeds cap, returns a value > cap early.
    """
    if items is not None:
        Gsub = G.subgraph(items).copy()
    else:
        Gsub = G.copy()

    if not nx.is_directed_acyclic_graph(Gsub):
        Gsub = break_cycles_make_dag(Gsub)

    # Conservative estimate: number of ideals is at most 2^(number of roots)
    roots = [n for n in Gsub.nodes() if Gsub.in_degree(n) == 0]
    r = len(roots)
    # guard against huge exponent
    if r >= 60:
        return float('inf')
    estimate = 2 ** r
    if cap is not None and estimate > cap:
        return estimate
    return estimate


def build_poset_from_sets(sets):
    unique_list = list(dict.fromkeys(sets))
    key_for = {s: '{' + ', '.join(sorted(s)) + '}' for s in unique_list}

    element_index = {}
    for idx, s in enumerate(unique_list):
        for e in s:
            element_index.setdefault(e, set()).add(idx)

    all_indices = set(range(len(unique_list)))
    children = {key_for[s]: [] for s in unique_list}

    for i, A in enumerate(unique_list):
        if len(A) == 0:
            candidates = all_indices - {i}
        else:
            lists = [element_index.get(e, set()) for e in A]
            candidates = set.intersection(*lists) if lists else set()
            candidates.discard(i)

        if not candidates:
            continue

        min_size = min(len(unique_list[j]) for j in candidates)
        minimal_supers = [j for j in candidates if len(unique_list[j]) == min_size]

        for j in minimal_supers:
            if A.issubset(unique_list[j]):
                children[key_for[A]].append(key_for[unique_list[j]])

    return children


def select_by_degree(G, k=12):
    deg = {n: G.in_degree(n) + G.out_degree(n) for n in G.nodes()}
    sorted_items = sorted(deg.items(), key=lambda x: (-x[1], x[0]))
    selected = [item for item, _ in sorted_items[:k]]
    # ensure we include prerequisites (ancestors) of selected items so the
    # induced subgraph contains roots and ideals can be generated
    expanded = set(selected)
    try:
        for it in selected:
            expanded |= set(nx.ancestors(G, it))
    except Exception:
        pass
    return list(expanded)


def save_hasse(poset_mapping, out_png):
    """Save a simple Hasse diagram (cover graph) as PNG using networkx + matplotlib.

    poset_mapping: dict where keys are state keys and values are list of immediate supersets
    out_png: output path
    """
    try:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
    except Exception:
        logger.error('matplotlib not available; cannot save Hasse diagram')
        return

    G = nx.DiGraph()
    for u, vs in poset_mapping.items():
        G.add_node(u)
        for v in vs:
            G.add_edge(u, v)

    plt.figure(figsize=(12, max(6, len(G.nodes()) // 10)))
    try:
        pos = nx.spring_layout(G, seed=42)
    except Exception:
        pos = None

    nx.draw_networkx_nodes(G, pos=pos, node_size=50)
    nx.draw_networkx_edges(G, pos=pos, arrows=False, width=0.5)
    nx.draw_networkx_labels(G, pos=pos, font_size=6)
    plt.axis('off')
    os.makedirs(os.path.dirname(out_png) or '.', exist_ok=True)
    plt.savefig(out_png, dpi=150, bbox_inches='tight')
    plt.close()
    logger.info('Saved Hasse diagram to %s', out_png)
